# config.toml
base_url = "https://marc0x71.github.io"
title = "~/il-codice-di-marco"
description = "Blog su Linux, Programmazione Rust, Neovim e Git"

theme = "terminal-gruvbox"

compile_sass = false

generate_feeds = true
feed_filenames = ["atom.xml"]

taxonomies = [
    {name = "tags", feed = true},
]

default_language = "it"

[languages.en]
title = "~/il-codice-di-marco"
description = "Blog about Linux, Rust programming, Neovim and Git"
generate_feeds = true  # ‚Üê Assicurati che ci sia!
feed_filenames = ["atom.xml"]

taxonomies = [
    {name = "tags", feed = true},
]

[markdown]
external_links_target_blank = true
smart_punctuation = true

# [markdown.highlighting]
# theme = "base16-ocean-dark"
